import pandas as pd
from fillpdf import fillpdfs
import os

df = pd.read_excel('form_fields.xlsx')

input_pdf_path = 'Source.pdf'
output_directory = 'output_pdfs'

if not os.path.exists(output_directory):
    os.makedirs(output_directory)

form_fields = fillpdfs.get_form_fields(input_pdf_path)
print("PDF Form Fields: ", form_fields)

for index, row in df.iterrows():
    data_dict = {
        # 'text_1gfsf': row['Name'] if 'Name' in df.columns else '',       
        'text_1usfw': row['B_N'] if 'B_N' in df.columns else '',
        'text_2vevm': row['PED'] if 'PED' in df.columns else '', 
        'text_3mcaz': row['DBA'] if 'DBA' in df.columns else '',
        'text_4caln': row['APP-N'] if 'APP-N' in df.columns else '',
        'text_5joua': row['APP_MA'] if 'APP_MA' in df.columns else '',
        'text_6ixkm': None, 
        'text_7mwou': None, 
        'text_8wngs': None, 
        'text_9mlrc': None, 
        'text_10sco': None, 
        'text_11qvbn': None, 
        'text_12ojps': None, 
        'text_13rzfv': None, 
        'text_14vfys': None, 
        'text_16kqsd': None, 
        'text_17ngak': None, 
        'text_18vcoj': None, 
        'text_19kqcg': None, 
        'text_20azuf': None, 
        'text_21zeo': None, 
        'text_22cfek': None, 
        'text_24yeig': None, 
        'text_25dzke': None, 
        'text_26ijew': None, 
        'text_27kbdz': None, 
        'text_28icek': None, 
        'text_29thju': None, 
        'text_30lq': None, 
        'text_31qbdp': None, 
        'text_32ktor': None, 
        'text_33xwbh': None, 
        'text_34wqjl': None, 
        'text_35aoro': None, 
        'text_36hztj': None, 
        'text_37sick': None, 
        'text_38fdvm': None, 
        'text_39nj': None, 
        'text_41gzbv': None, 
        'text_42zsbi': None, 
        'text_43pjtf': None, 
        'text_44qcpg': None, 
        'text_45utan': None, 
        'text_46kukr': None, 
        'text_47ghwa': None, 
        'text_48flqu': None, 
        'text_49rwfc': None, 
        'text_50punk': None, 
        'text_51mptk': None, 
        'text_52ecfx': None, 
        'text_53rqvq': None, 
        'text_54jpci': None, 
        'text_55vtty': None, 
        'text_56akfi': None, 
        'text_57yrjg': None, 
        'text_58xduk': None, 
        'text_59macs': None, 
        'text_60emtr': None, 
        'text_61xzrz': None, 
        'text_62qmxe': None, 
        'text_63hizi': None, 
        'text_64tqrt': None, 
        'text_65fdry': None, 
        'text_66muoj': None, 
        'text_67free': None, 
        'text_68swq': None, 
        'text_69voun': None, 
        'text_70knim': None, 
        'text_71dzwd': None, 
        'text_72qwdg': None, 
        'text_73pyok': None, 
        'text_74tyzh': None, 
        'text_75dsos': None, 
        'text_76lw': None, 
        'text_77xzpp': None, 
        'text_78bhni': None, 
        'text_79hfil': None, 
        'text_80tito': None, 
        'text_81exrm': None, 
        'text_82yoed': None, 
        'text_83opsz': None, 
        'text_84pizk': None, 
        'text_85iloc': None, 
        'text_86euqs': None, 
        'text_87qtft': None, 
        'text_88gert': None, 
        'text_89wded': None, 
        'text_90ikym': None, 
        'text_91ixhf': None,
        'text_92iva': None, 
        'text_93ewxn': None, 
        'text_94gjck': None, 
        'text_95xbhn': None, 
        'text_96fags': None, 
        'text_97umac': None, 
        'text_98lqti': None, 
        'text_99ykxh': None, 
        'text_100ohpr': None, 
        'text_101oezd': None, 
        'text_102pvrk': None, 
        'text_103aeb': None, 
        'text_104ffrf': None, 
        'text_105ox': None, 
        'text_106fqmu': None, 
        'text_107xluj': None, 
        'text_108smha': None, 
        'text_109ltgj': None, 
        'text_110ctmm': None, 
        'text_111euqn': None, 
        'text_112iudg': None, 
        'text_113srof': None, 
        'text_114mgvg': None, 
        'text_115gmpe': None, 
        'text_116ymjb': None, 
        'text_117hqxb': None, 
        'text_120xlke': None, 
        'text_121bgos': None, 
        'text_122dft': None, 
        'text_123sagd': None, 
        'text_124emvl': None, 
        'text_125qwjj': None, 
        'text_126gkrw': None, 
        'text_127rki': None, 
        'text_128wen': None, 
        'text_129belv': None, 
        'text_130vnqx': None, 
        'text_131xhaj': None, 
        'text_132xzyf': None, 
        'text_133ouja': None, 
        'text_134irax': None, 
        'text_135kweg': None, 
        'text_136ugjj': None, 
        'text_137tjhw': None, 
        'text_138iuqh': None, 
        'text_139yidl': None, 
        'text_140mbva': None, 
        'text_141ogb': None, 
        'text_142qmk': None, 
        'text_143ncda': None, 
        'text_144rvs': None, 
        'text_145ty': None, 
        'text_146bdsc': None, 
        'text_147psaq': None, 
        'text_148scdb': None, 
        'text_149ixmg': None, 
        'text_150fsgv': None, 
        'text_151jzc': None, 
        'text_152ggxx': None, 
        'text_153qkii': None, 
        'text_154nbtf': None, 
        'text_155hcdd': None, 
        'text_156avow': None, 
        'text_157hwwu': None
    }

    output_pdf_path = os.path.join(output_directory, f'filled_form_{index + 1}.pdf')

    fillpdfs.write_fillable_pdf(input_pdf_path, output_pdf_path, data_dict)

    print(f'Generated {output_pdf_path}')

print("All PDFs generated successfully!")
